language: julia
julia:
  - nightly
  - 0.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base texlive-binaries pdf2svg
script:
  - julia generateGreedy.jl
  - julia generateSpantree.jl
  - julia generateDijkstraOnestep.jl
  - julia generateDijkstraFull.jl
  - julia generateKnapsack.jl
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PACKAGE_NAME")); include(joinpath("docs", "make.jl"))'
