language: julia
julia:
    #  - nightly
  - 0.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-binaries pdf2svg
  - julia -e 'for p in ["TikzPictures", "LightXML", "Combinatorics"] Pkg.add(p) end'
  - sed -i '109s/.*/        Base.@__doc__ $f($(args...),)::$rettype =/g' ~/.julia/v0.6/Memoize/src/Memoize.jl
script:
  - julia generateGreedy.jl
  - julia generateSpantree.jl
  - julia generateDijkstraOnestep.jl
  - julia generateDijkstraFull.jl
  - julia generateKnapsack.jl
  - julia generateMaxFlow.jl
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia docs/make.jl
